#!/bin/bash

hn=`hostname | rev | cut -d '-' -f 1 | rev `

uid=${hn:2}

cd /home/jovyan


[ `cat /etc/resolv.conf | grep turing | wc -l` == 1 ] && teetoodapa --port 8000 --host 0.0.0.0 --root-path /user/terradue-ogctb1-nt-fastapi-dapa-${uid}/proxy/8000 &

[ `cat /etc/resolv.conf | grep google | wc -l` == 1 ] && teetoodapa --port 8000 --host 0.0.0.0 --root-path /user/terradue-ogctb1-nt-fastapi-dapa-${uid}/proxy/8000 &

[ `cat /etc/resolv.conf | grep ovh | wc -l` == 1 ] && teetoodapa --port 8000 --host 0.0.0.0 --root-path /user/terradue-ogctb1-nt-fastapi-dapa-${uid}/proxy/8000 &

[ `cat /etc/resolv.conf | grep gesis | wc -l` == 1 ] && teetoodapa --port 8000 --host 0.0.0.0 --root-path /binder/jupyter/user/terradue-ogctb1-nt-fastapi-dapa-${uid}/proxy/8000 &

# dcoumentation 
mkdocs serve -a 0.0.0.0:8001 &

xserve &

exec "$@"
